rootProject.name = "multiple-module-spring-boot"

include("common:common-base")
include("common:common-domain")
include("common:common-infrastructure:event-base")
include("common:common-infrastructure:event-core")
include("common:common-infrastructure:event-spring")

include("provider:starter")
include("provider:type")
include("provider:api")
include("provider:application")
include("provider:domain")
include("provider:infrastructure")
include("provider:adapter")

include("consumer:starter")
include("consumer:type")
include("consumer:api")
include("consumer:application")
include("consumer:domain")
include("consumer:infrastructure")
include("consumer:adapter")

include("auth:starter")
include("auth:type")
include("auth:api")
include("auth:application")
include("auth:domain")
include("auth:infrastructure")
include("auth:adapter")
